### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by mishelashala** [KriegerMx/MapatonAPI#1]
# Normalizar los puntos de entrada (endpoints)
## Principios de REST
1. Todo es un recurso
2. Todo puede ser representado de diferentes formas
   - json
   - xml
   - blob
## Principios de API
1. Todo es una acción
   - GET
   - POST
   - PUT
   - DELETE
## REST + API
1. Obtener todos los recursos (posts)  
   `GET /api/posts/`
2. Obtener un recurso por id  
   `GET /api/posts/:id`
3. Crear un recurso nuevo  
   `POST /api/posts/`
4. Actualizar un recurso  
   `PUT /api/posts/:id`
5. Eliminar un recurso  
   `DELETE /api/posts/:id`

**Comment by kuanb** [comment]
I would like the 2nd the above post - I think a RESTful API would be a far more effective mechanism of distribution. In addition, it would allow static web pages focused on visualization components to operate as standalone products.

**Comment by CristianKrieger** [comment]
Las APIs son REST.
Si usan el API Explorer, al hacer la petición se muestra el formato:

POST https://mapaton-public.appspot.com/_ah/api/dashboardAPI/v1/getAllGtfsTrails
{
 "numberOfElements": 20
}
