### ISSUE TITLE
¿Cómo utilizar el cursor?

### ISSUE THREAD

**Issue by mishelashala** [KriegerMx/MapatonAPI#2]
# NO esta documentado.

El uso de cursor (para paginación de resultados) no esta documentado. 
## ¿cómo lo uso?

¿Cómo parametro? ¿Cómo cabecera? ¿Cómo un token?

**Comment by CristianKrieger** [comment]
# SI ESTA DOCUMENTADO

dashboardAPI.getAllTrails, dashboardAPI.getAllValidTrails, dashboardAPI.getAllGtfsTrails,

Método utilizado para obtener todos los recorridos guardados, los recorridos se encuentran paginados y es necesario indicar al servidor el tamaño y el número de la página.

Parámetros:

cursor: Una cadena de texto que puede estar vacía que le indica al servidor el número de la página que se desea obtener. Para obtener la primer página se llama con una cadena vacía, para páginas posteriores, se utiliza una cadena que el servidor regresa después de cada petición llamada también cursor
numberOfElements: Un entero que indica el número de elementos que uno desea que el servidor regrese
Retornos:

cursor: Una cadena de texto utilizada para mandar al servidor y obtener el siguiente grupo de elementos paginados.
trails: Un arreglo de recorridos del número de elementos solicitado por numberOfElements. Los recorridos tienen todos los datos de recorrido detallados en dashboardAPI.getTrailDetails.
