### ISSUE TITLE
Data dump access

### ISSUE THREAD

**Issue by kuanb** [KriegerMx/MapatonAPI#3]
Is there a `dump.sql` of the entire database? This API allows for some specific lines of inquiry but is there perhaps a way to access the full data base? Would there be a location where a copy of the SQL DB is held? I imagine the size is large but not unreasonable. Perhaps a simple Dropbox link would suffice.

**Comment by CristianKrieger** [comment]
This is not an SQL DB and the Google Datastore doesn't support dumping data to a file.
If this feature is truly needed, a translation script must be developed.
